# Generated by Django 4.2.6 on 2023-10-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiposExames',
        ),
    ]
